In [1]:
import random
import torch
import numpy as np
import pandas as pd
import einops

### Initialization - basic

In [23]:
N = np.array([[1,2,3],[4,5,6]], dtype=np.float32) # if not copy: np.asarray (auto arrange), np.asanyarray (any arrange), np.ascontiguousarray (cont arrage)
# more: np.ones, np.zeros, np.identity(n:int)
T = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)

print( np.arange(0,1,0.1), np.linspace(0,1,11) )

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9] [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Initialization - random

In [10]:
# numpy
np.random.seed(7)
print( np.random.random((2,3)) ) # uniform 0~1, same as np.empty
print( np.random.rand(2,3) ) # same as above but easier notation

print( np.random.normal(0.0, 1.0, (2,3)) ) # mean, std, size (if none reutrns a number)
print( np.random.randn(2,3) ) # same as above but easier notation + cannot specified mean and std

print( np.random.randint(0, 6, (2,3)) ) # [lb,ub)
print( np.random.uniform(0, 6, (2,3)) ) # float version of above

print( np.empty_like(np.array([1])) ) # e.g. np.ones_like, np.zeros_like

# torch
torch.manual_seed(7)
print( torch.rand(2,3) )
print( torch.randn(2,3) )
print( torch.randint(0, 6, (2,3)) )

[[0.07630829 0.77991879 0.43840923]
 [0.72346518 0.97798951 0.53849587]]
[[0.50112046 0.07205113 0.26843898]
 [0.4998825  0.67923    0.80373904]]
[[-0.62542897 -0.17154826  0.50529937]
 [-0.26135642 -0.24274908 -1.45324141]]
[[ 0.55458031  0.12388091  0.27445992]
 [-1.52652453  1.65069969  0.15433554]]
[[0 1 0]
 [0 5 4]]
[[2.23430814 2.86440693 2.19534231]
 [5.02750797 4.61188504 1.88396806]]
[0]
tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]])
tensor([[-1.2514, -1.8841,  0.4457],
        [-0.7068, -1.5750, -0.6318]])
tensor([[3, 0, 0],
        [4, 5, 3]])


In [4]:
print( torch.randperm(4) ) # tensor([2, 1, 0, 3])
print( torch.multinomial(input=torch.tensor([0.2, 0.8]), num_samples=10, replacement=True) )

tensor([1, 3, 2, 0])
tensor([1, 1, 1, 0, 1, 1, 1, 1, 1, 1])


### Computation

In [12]:

L = dir(np.array([[1,2,3],[4,5,6]]))
print(dir(L))

# vectorization operator and selection


['__add__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


### Where selection

In [98]:
# where(bool_vectorized, target, otherwise_val)

L = np.array([[1,2,3], [4,5,6]])
print( np.where(L<3, L, -1) ) # cannot be arr.where

df = pd.DataFrame(L)
print( df.where(df<3, -1) )

ser = pd.Series([1,3,5])
print( ser.where(ser<3, -1) )

T = torch.tensor(L)
print( T.where(T<3, -1) )
print( torch.where(T<3, T, -1) )

[[ 1  2 -1]
 [-1 -1 -1]]
   0  1  2
0  1  2 -1
1 -1 -1 -1
0    1
1   -1
2   -1
dtype: int64
tensor([[ 1,  2, -1],
        [-1, -1, -1]])
tensor([[ 1,  2, -1],
        [-1, -1, -1]])


In [106]:
# argwhere: non zero index
L = np.array([1,0,2])
print( np.argwhere(L) ) # cannot be arr.where

T = torch.tensor([1,0,2])
print( torch.argwhere(T) )
print( T.argwhere() )

[[0]
 [2]]
tensor([[0],
        [2]])
tensor([[0],
        [2]])


### Random

In [62]:
L = np.array([1,2,3,4,5,6])
print( np.random.choice(L, 6) ) # L must be 1 dim
print( np.random.choice(L, 6, replace=False) ) # no duplicate
np.random.shuffle(L)
print(L)

L = [1,2,3,4,5,6]
random.shuffle(L)
print(L)
print(random.sample(L, 6)) # no duplicate
print(random.choices(L, k=6))


[2 6 5 4 5 1]
[6 4 1 5 3 2]
[5 3 6 1 2 4]
[6, 5, 4, 3, 1, 2]
[2, 3, 4, 1, 5, 6]
[4, 2, 4, 3, 3, 1]


### Concat

In [44]:
L1, L2 = np.array([[1,2,3]]), np.array([[4,5,6]])
print( np.concatenate((L1,L2), axis=0) )

T1, T2 = torch.tensor(L1), torch.tensor(L2)
print( torch.cat((T1, T2), dim=0) )

s1, s2 = pd.Series([1,2,3]), pd.Series([4,5,6])
print( pd.concat((s1, s2), axis=1) )
print( pd.concat((s1, s2), axis=0) )


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])
   0  1
0  1  4
1  2  5
2  3  6
0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64


### Rearrange

In [80]:
T = torch.tensor([[1,2,3], [4,5,6]])
print( einops.rearrange(T, 'B C -> C B') )
print( einops.repeat(T, 'h w -> h w c', c=3) )

T = torch.rand(1,3,16,16)
print( einops.reduce(T, 'b c (h h2) (w w2) -> b h w c', 'mean', h2=2, w2=2).shape )

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 1, 1],
         [2, 2, 2],
         [3, 3, 3]],

        [[4, 4, 4],
         [5, 5, 5],
         [6, 6, 6]]])
torch.Size([1, 8, 8, 3])


### Sort

In [97]:
L = np.array([30, 10, 20]) # rank_idx=[2,0,1] # find_idx=[1,2,0]
find_idx = np.argsort(L)
print(find_idx)
print(L[find_idx]) # sorted

L.sort()
print(L)

print('---')

T = torch.tensor([30, 10, 20])
find_idx = T.argsort()
print(find_idx)
print(T[find_idx]) # sorted

A, B = T.sort()
print(A, B)

[1 2 0]
[10 20 30]
[10 20 30]
---
tensor([1, 2, 0])
tensor([10, 20, 30])
tensor([10, 20, 30]) tensor([1, 2, 0])


### Equal check
+ “==” check value, “is” check pointer (more strict)
+ Int, float, bool check value, obj if not specified __equal__ the default is same as “is”
+ tuple, string, list, set, dict: automatically iterate and recursive if needed

In [123]:
L, M = np.array([1,2,3,4]), np.array([1,2,1,2])
print(L==M, np.equal(L, M))
print( np.array_equal(L, M) )

T, U = torch.tensor([1,2,3,4]), torch.tensor([1,2,1,2])
print(T==U, torch.eq(T, U))
print( torch.equal(T, U) )


[ True  True False False] [ True  True False False]
False
tensor([ True,  True, False, False]) tensor([ True,  True, False, False])
False


### More

In [168]:
T1 = torch.Tensor( [[1,2,3],[4,5,6]] ) # or torch.Tensor( np.array([[1,2,3],[4,5,6]]) )
T2 = torch.zeros(2,3) # or torch.ones(2,3)
T3 = torch.rand(2,3) # 0~1
print(T1, type(T1), T1.shape, T1.dtype, T1.device, T1.requires_grad)
print(T2, type(T2), T2.shape, T2.dtype, T2.device, T3.requires_grad)
print(T3, type(T3), T3.shape, T3.dtype, T3.device, T3.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) <class 'torch.Tensor'> torch.Size([2, 3]) torch.float32 cpu False
tensor([[0., 0., 0.],
        [0., 0., 0.]]) <class 'torch.Tensor'> torch.Size([2, 3]) torch.float32 cpu False
tensor([[0.7433, 0.8812, 0.0512],
        [0.4459, 0.6041, 0.0789]]) <class 'torch.Tensor'> torch.Size([2, 3]) torch.float32 cpu False


In [183]:
T = torch.Tensor( [[1,2,3],[4,5,6]] )
print("numpy:", T.numpy())

T = T.type(torch.float64)
print("change_type:", T)
T = T.to('cuda')
print("change_device:", T)
T.requires_grad=True # float type only
print("change_trainable:", T)

print(T.cpu().detach().numpy()) # T.numpy() will failed

numpy: [[1. 2. 3.]
 [4. 5. 6.]]
change_type: tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
change_device: tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float64)
change_trainable: tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float64,
       requires_grad=True)
[[1. 2. 3.]
 [4. 5. 6.]]


In [199]:
T = torch.Tensor( [[1,2,3],[4,5,6]] )
print( len(T), T[0], T[0][0] )
print(T+2, T-2, T*2, T/2)
print(T+T, T-T, T*T, T/T)
print(T.T)
print(T.matmul(T.T) )

2 tensor([1., 2., 3.]) tensor(1.)
tensor([[3., 4., 5.],
        [6., 7., 8.]]) tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]]) tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]) tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[14., 32.],
        [32., 77.]])


In [170]:
print( dir(T1) )

['T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rmul__', '__rpow__', '__rshift__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__set

In [171]:
T = torch.Tensor([[0,1,-2],[-3,-4,5]])
print( "numpy:", T.numpy() )
print( "abs:", (-T).abs() )
print( "sin:", T.sin() )
print( "mean:", T.mean(axis=1) )
print( "std:", T.std(axis=1) )
print( "flatten:", T.flatten() )
print( "reshape:", T.reshape(3,2) )
print( "permute:", T.permute(1,0) )
# or torch.xxx(T,args) e.g. torch.mean(T,axis=1)

numpy: [[ 0.  1. -2.]
 [-3. -4.  5.]]
abs: tensor([[0., 1., 2.],
        [3., 4., 5.]])
sin: tensor([[ 0.0000,  0.8415, -0.9093],
        [-0.1411,  0.7568, -0.9589]])
mean: tensor([-0.3333, -0.6667])
std: tensor([1.5275, 4.9329])
flatten: tensor([ 0.,  1., -2., -3., -4.,  5.])
reshape: tensor([[ 0.,  1.],
        [-2., -3.],
        [-4.,  5.]])
permute: tensor([[ 0., -3.],
        [ 1., -4.],
        [-2.,  5.]])


In [172]:
T = torch.Tensor([[0,5,-2],[-3,-4,1]])
values, indices = T.max(axis=1)
print(values, indices)

values, indices = T.max(axis=1)[0].sort()
print(values, indices)

tensor([5., 1.]) tensor([1, 2])
tensor([1., 5.]) tensor([1, 0])


In [173]:
T = torch.Tensor([[1,2,3],[4,5,6]])
U = T.clone()
U.apply_(lambda d:d*2) # modify directly without return # end with _ means directly change
print( T, U )

tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [174]:
T1 = torch.Tensor( [[1,2,3],[4,5,6]] )
T2 = torch.Tensor( [[7,8,9],[10,11,12]] )
print("cat0:", torch.cat([T1,T2],axis=0) )
print("cat1:", torch.cat([T1,T2],axis=1) )
print("stack:", torch.stack([T1,T2]) )

cat0: tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
cat1: tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])
stack: tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [175]:
T = torch.Tensor([[[1,2,3]]])
print("original:", T, T.shape)
U = T.squeeze()
print("squeeze:", U, U.shape )
V = U.unsqueeze(axis=0)
print("unsqueeze:", V, V.shape)

original: tensor([[[1., 2., 3.]]]) torch.Size([1, 1, 3])
squeeze: tensor([1., 2., 3.]) torch.Size([3])
unsqueeze: tensor([[1., 2., 3.]]) torch.Size([1, 3])
