In [1]:
import torch
from torch.utils.data import TensorDataset, DataLoader

X = torch.Tensor([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
y = torch.Tensor([1,2,3,4])

dataset = TensorDataset(X,y)
for x,y in dataset:
    print(x,y)

tensor([1., 1., 1.]) tensor(1.)
tensor([2., 2., 2.]) tensor(2.)
tensor([3., 3., 3.]) tensor(3.)
tensor([4., 4., 4.]) tensor(4.)


In [10]:
for batch in DataLoader(dataset=dataset, batch_size=2):
    print(batch)

[tensor([[1., 1., 1.],
        [2., 2., 2.]]), tensor([1., 2.])]
[tensor([[3., 3., 3.],
        [4., 4., 4.]]), tensor([3., 4.])]


In [12]:
for batch in DataLoader(dataset=dataset, batch_size=2, collate_fn=lambda x:x):
    print(batch)

[(tensor([1., 1., 1.]), tensor(1.)), (tensor([2., 2., 2.]), tensor(2.))]
[(tensor([3., 3., 3.]), tensor(3.)), (tensor([4., 4., 4.]), tensor(4.))]


In [50]:
def collate_fn(x): # input a batch dataXY
    print(">>", x)
    batch = []
    for j in range(len(x[0])):  # j=0,1 due to X,Y
        M = []                  # List for each X,Y
        for i in range(len(x)): # i=index_in_batch 
            M.append( x[i][j].unsqueeze(0) )
        batch.append( torch.cat(M,0) )
    return batch

for batch in DataLoader(dataset=dataset, batch_size=2, collate_fn=collate_fn):
    print(batch)

>> [(tensor([1., 1., 1.]), tensor(1.)), (tensor([2., 2., 2.]), tensor(2.))]
[tensor([[1., 1., 1.],
        [2., 2., 2.]]), tensor([1., 2.])]
>> [(tensor([3., 3., 3.]), tensor(3.)), (tensor([4., 4., 4.]), tensor(4.))]
[tensor([[3., 3., 3.],
        [4., 4., 4.]]), tensor([3., 4.])]
