### CUDA
+ Packages:
    + driver can't exist multiple versions but cudatoolkit can
    | package | command | function | version |
    | - | - | - | - |
    | CUDA driver by NVIDIA | nvidia-smi | show driver version and lastest cudatoolkit version | e.g. 470.xxx |
    | cudatoolkit by NVIDIA | nvcc --version | complete package includes bin and lib | e.g. /usr/local/cuda-11.2 |
    | cudatoolkit by Conda  | conda list cudatoolkit \| torch.version.cuda | Dynamic lib without bin for DL | e.g. ~/miniconda3/pkgs/cudatoolkit-10.1.243 |
    
+ Installation: Install 1 and 3 and is enough for DL
    1. [NVIDIA driver](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html)
    2. [NVIDIA cudatoolkit](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_local)
    3. [conda cudatoolkit+Pytorch](https://pytorch.org/get-started/previous-versions/)

+ Env path:
    | paths had to be set | meaning | e.g. |
    | - | - | - |
    | CUDA_HOME > CUDA_PATH > /usr/local/cuda* | cudatoolkit path | /usr/local/cuda* |
    | PATH | cudatoolkit path | /usr/local/cuda* |
    | LD_LIBRARY_PATH | compiling lib path | /usr/local/cuda*/lib64 |

+ Pip:
    + /usr/lib/python3/dist-packages: sudo apt install python-numpy
    + /usr/local/lib/python3.6/dist-packages: sudo pip install numpy
    + ~/.local/lib/python3.6/site-packages: pip install numpy
    + Base env will share its packages to all envs. Do conda install -n <envs> pip to seperate packages in new env.

+ Reference:
    + [cuda和cudatoolkit](https://iter01.com/561967.html)
    + [Installing Multiple CUDA & cuDNN Versions in Ubuntu](https://towardsdatascience.com/installing-multiple-cuda-cudnn-versions-in-ubuntu-fcb6aa5194e2)

### Device

In [4]:
import torch
import numpy as np

print(torch.cuda.is_available(), torch.backends.cudnn.is_available(), torch.cuda.get_device_name(0))
device = torch.device('cuda')
print(device)

True True NVIDIA GeForce GTX 1650 with Max-Q Design
cuda


### Tensor

In [168]:
T1 = torch.Tensor( [[1,2,3],[4,5,6]] ) # or torch.Tensor( np.array([[1,2,3],[4,5,6]]) )
T2 = torch.zeros(2,3) # or torch.ones(2,3)
T3 = torch.rand(2,3) # 0~1
print(T1, type(T1), T1.shape, T1.dtype, T1.device, T1.requires_grad)
print(T2, type(T2), T2.shape, T2.dtype, T2.device, T3.requires_grad)
print(T3, type(T3), T3.shape, T3.dtype, T3.device, T3.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) <class 'torch.Tensor'> torch.Size([2, 3]) torch.float32 cpu False
tensor([[0., 0., 0.],
        [0., 0., 0.]]) <class 'torch.Tensor'> torch.Size([2, 3]) torch.float32 cpu False
tensor([[0.7433, 0.8812, 0.0512],
        [0.4459, 0.6041, 0.0789]]) <class 'torch.Tensor'> torch.Size([2, 3]) torch.float32 cpu False


In [183]:
T = torch.Tensor( [[1,2,3],[4,5,6]] )
print("numpy:", T.numpy())

T = T.type(torch.float64)
print("change_type:", T)
T = T.to('cuda')
print("change_device:", T)
T.requires_grad=True # float type only
print("change_trainable:", T)

print(T.cpu().detach().numpy()) # T.numpy() will failed

numpy: [[1. 2. 3.]
 [4. 5. 6.]]
change_type: tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
change_device: tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float64)
change_trainable: tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', dtype=torch.float64,
       requires_grad=True)
[[1. 2. 3.]
 [4. 5. 6.]]


In [199]:
T = torch.Tensor( [[1,2,3],[4,5,6]] )
print( len(T), T[0], T[0][0] )
print(T+2, T-2, T*2, T/2)
print(T+T, T-T, T*T, T/T)
print(T.T)
print(T.matmul(T.T) )

2 tensor([1., 2., 3.]) tensor(1.)
tensor([[3., 4., 5.],
        [6., 7., 8.]]) tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]]) tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]) tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[14., 32.],
        [32., 77.]])


In [170]:
print( dir(T1) )

['T', '__abs__', '__add__', '__and__', '__array__', '__array_priority__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__div__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rdiv__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rfloordiv__', '__rmul__', '__rpow__', '__rshift__', '__rsub__', '__rtruediv__', '__setattr__', '__setitem__', '__set

In [171]:
T = torch.Tensor([[0,1,-2],[-3,-4,5]])
print( "numpy:", T.numpy() )
print( "abs:", (-T).abs() )
print( "sin:", T.sin() )
print( "mean:", T.mean(axis=1) )
print( "std:", T.std(axis=1) )
print( "flatten:", T.flatten() )
print( "reshape:", T.reshape(3,2) )
print( "permute:", T.permute(1,0) )
# or torch.xxx(T,args) e.g. torch.mean(T,axis=1)

numpy: [[ 0.  1. -2.]
 [-3. -4.  5.]]
abs: tensor([[0., 1., 2.],
        [3., 4., 5.]])
sin: tensor([[ 0.0000,  0.8415, -0.9093],
        [-0.1411,  0.7568, -0.9589]])
mean: tensor([-0.3333, -0.6667])
std: tensor([1.5275, 4.9329])
flatten: tensor([ 0.,  1., -2., -3., -4.,  5.])
reshape: tensor([[ 0.,  1.],
        [-2., -3.],
        [-4.,  5.]])
permute: tensor([[ 0., -3.],
        [ 1., -4.],
        [-2.,  5.]])


In [172]:
T = torch.Tensor([[0,5,-2],[-3,-4,1]])
values, indices = T.max(axis=1)
print(values, indices)

values, indices = T.max(axis=1)[0].sort()
print(values, indices)

tensor([5., 1.]) tensor([1, 2])
tensor([1., 5.]) tensor([1, 0])


In [173]:
T = torch.Tensor([[1,2,3],[4,5,6]])
U = T.clone()
U.apply_(lambda d:d*2) # modify directly without return # end with _ means directly change
print( T, U )

tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [174]:
T1 = torch.Tensor( [[1,2,3],[4,5,6]] )
T2 = torch.Tensor( [[7,8,9],[10,11,12]] )
print("cat0:", torch.cat([T1,T2],axis=0) )
print("cat1:", torch.cat([T1,T2],axis=1) )
print("stack:", torch.stack([T1,T2]) )

cat0: tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
cat1: tensor([[ 1.,  2.,  3.,  7.,  8.,  9.],
        [ 4.,  5.,  6., 10., 11., 12.]])
stack: tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])


In [175]:
T = torch.Tensor([[[1,2,3]]])
print("original:", T, T.shape)
U = T.squeeze()
print("squeeze:", U, U.shape )
V = U.unsqueeze(axis=0)
print("unsqueeze:", V, V.shape)

original: tensor([[[1., 2., 3.]]]) torch.Size([1, 1, 3])
squeeze: tensor([1., 2., 3.]) torch.Size([3])
unsqueeze: tensor([[1., 2., 3.]]) torch.Size([1, 3])
